before_script:
  - apt-get update && apt-get install -y maven
​
image: openjdk:18-slim
​
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
​
cache:
  paths:
    - .m2/repository
​
build:
  stage: build
  script:
    - mvn clean package -DskipTests
​
tests:
  stage: test
  script:
    - mvn test
